Repository SE2-Mankomania-SS20/Mankomania, pull requests merged in 2020-05, with the labels that each got.

#80 Feature/notificationsystem
  gamecore/src/main/java/com/mankomania/game/gamecore/MankomaniaGame.java
  gamecore/src/main/java/com/mankomania/game/gamecore/client/ClientChat.java
  gamecore/src/main/java/com/mankomania/game/gamecore/notificationsystem/Notification.java
  gamecore/src/main/java/com/mankomania/game/gamecore/notificationsystem/Notifier.java
  gamecore/src/main/java/com/mankomania/game/gamecore/screens/AbstractScreen.java
  gamecore/src/main/java/com/mankomania/game/gamecore/screens/ChatScreen.java
  gamecore/src/main/java/com/mankomania/game/gamecore/screens/DiceScreen.java
  gamecore/src/main/java/com/mankomania/game/gamecore/screens/LaunchScreen.java
  gamecore/src/main/java/com/mankomania/game/gamecore/screens/LobbyScreen.java
  gamecore/src/main/java/com/mankomania/game/gamecore/screens/MainGameScreen.java
Labels: feature

#81 Hotfix/version update
  build.gradle
  core/build.gradle
  core/src/test/java/com/mankomania/game/core/player/TestPlayer.java
  gamecore/build.gradle
  gamecore/src/test/java/com/mankomania/game/gamecore/client/ClientChatTest.java
  server/build.gradle
Labels: enhancement

#85 Hotfix/refactor
  core/src/main/java/com/mankomania/game/core/data/GameData.java
  core/src/main/java/com/mankomania/game/core/fields/FieldDataLoader.java
  core/src/main/java/com/mankomania/game/core/network/messages/PlayerGameReady.java
  core/src/main/java/com/mankomania/game/core/network/messages/clienttoserver/PlayerDisconnected.java
  core/src/main/java/com/mankomania/game/core/network/messages/servertoclient/DisconnectPlayer.java
  core/src/main/java/com/mankomania/game/core/network/messages/servertoclient/InitPlayers.java
  gamecore/src/main/java/com/mankomania/game/gamecore/MankomaniaGame.java
  gamecore/src/main/java/com/mankomania/game/gamecore/client/NetworkClient.java
  gamecore/src/main/java/com/mankomania/game/gamecore/fieldoverlay/FieldOverlayTextures.java
  gamecore/src/main/java/com/mankomania/game/gamecore/hud/HUD.java
  gamecore/src/main/java/com/mankomania/game/gamecore/screens/ChatScreen.java
  gamecore/src/main/java/com/mankomania/game/gamecore/screens/DiceScreen.java
  gamecore/src/main/java/com/mankomania/game/gamecore/screens/LaunchScreen.java
  gamecore/src/main/java/com/mankomania/game/gamecore/screens/LobbyScreen.java
  gamecore/src/main/java/com/mankomania/game/gamecore/screens/MainGameScreen.java
  gamecore/src/main/java/com/mankomania/game/gamecore/util/Vector3Helper.java
  server/src/main/java/com/mankomania/game/server/Main.java
  server/src/main/java/com/mankomania/game/server/game/NetworkServer.java
Labels: bug

#91 Postion3 -> Vector3 and connection bug/issue
  core/src/main/java/com/mankomania/game/core/data/GameData.java
  core/src/main/java/com/mankomania/game/core/fields/FieldDataLoader.java
  core/src/main/java/com/mankomania/game/core/fields/Position3.java
  core/src/main/java/com/mankomania/game/core/fields/types/Field.java
  core/src/main/java/com/mankomania/game/core/fields/types/GainMoneyField.java
  core/src/main/java/com/mankomania/game/core/fields/types/HotelField.java
  core/src/main/java/com/mankomania/game/core/fields/types/JumpField.java
  core/src/main/java/com/mankomania/game/core/fields/types/LoseMoneyField.java
  core/src/main/java/com/mankomania/game/core/fields/types/LotterieField.java
  core/src/main/java/com/mankomania/game/core/fields/types/MinigameField.java
  core/src/main/java/com/mankomania/game/core/fields/types/PayLotterieField.java
  core/src/main/java/com/mankomania/game/core/fields/types/SpecialField.java
  core/src/main/java/com/mankomania/game/core/fields/types/StartField.java
  core/src/main/java/com/mankomania/game/core/fields/types/StockField.java
  core/src/main/java/com/mankomania/game/core/player/Player.java
  core/src/test/java/com/mankomania/game/core/data/TestGameData.java
  core/src/test/java/com/mankomania/game/core/player/TestPlayer.java
  gamecore/src/main/java/com/mankomania/game/gamecore/MankomaniaGame.java
  gamecore/src/main/java/com/mankomania/game/gamecore/client/NetworkClient.java
  gamecore/src/main/java/com/mankomania/game/gamecore/screens/LaunchScreen.java
  gamecore/src/main/java/com/mankomania/game/gamecore/screens/LobbyScreen.java
  gamecore/src/main/java/com/mankomania/game/gamecore/screens/MainGameScreen.java
  gamecore/src/main/java/com/mankomania/game/gamecore/util/Vector3Helper.java
  server/src/main/java/com/mankomania/game/server/game/NetworkServer.java
Labels: bug, enhancement

#93 Feature/gamecontroller
  core/src/main/java/com/mankomania/game/core/data/GameController.java
  core/src/main/java/com/mankomania/game/core/data/GameData.java
  core/src/test/java/com/mankomania/game/core/data/TestGameData.java
  gamecore/src/main/java/com/mankomania/game/gamecore/MankomaniaGame.java
Labels: bug
